services:
  postgres:
    image: postgres:16-alpine
    container_name: honodb
    environment:
      POSTGRES_DB: honodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
